---
- name: Import the NodeSource GPG key into apt
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Add NodeSource deb repository
  apt_repository:
    repo: 'deb https://deb.nodesource.com/node_{{ debian_node_version }} {{ ansible_distribution_release }} main'
    state: present

- name: Install base packages
  apt: pkg={{ item }} state=present
  with_items:
    - git
    - gzip
    - curl
    - python
    - libssl-dev
    - pkg-config
    - build-essential
    - apt-transport-https
    - nodejs

- name: Install mysql client for debugging
  apt: pkg=mysql-client-core-5.6 state=present
