---
- name: Install etherpad plugins
  npm: name={{ item }} path=/usr/local/etherpad-lite/node_modules production=yes
  with_items:
    - ep_tables2
    - ep_adminpads
    - ep_pad-lister

- name: Remove unwanted etherpad plugins
  npm: name={{ item }} path=/usr/local/etherpad-lite/node_modules production=yes state=absent
  with_items:
    - ep_list_pads
