---
- name: Install Etherpad
  hosts: etherpad
  tasks:
    - include: tasks/etherpad/install_etherpad.yaml
    - include: tasks/etherpad/create_etherpad_user.yaml
    - include: tasks/etherpad/clone_etherpad.yaml
    - include: tasks/etherpad/configure_etherpad.yaml
    - include: tasks/etherpad/start_etherpad.yaml
